# Site settings
title: HiTRACE
email: rhiju@stanford.edu
description: ""
baseurl: ""
url: "http://hitrace.github.io"
github_username:  hitrace

# Default variables
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      level: 1
      title: 
      author: "Siqi Tian"
  -
    scope:
      path: "hitrace"
    values:
      title: "HiTRACE"
      description: "<u>Hi</u>gh-<u>T</u>hroughput <u>R</u>obust <u>A</u>nalysis for <u>C</u>apillary <u>E</u>lectrophoresis"
      repo: "hitrace/HiTRACE"
      root: "/HiTRACE/"
  -
    scope:
      path: "rdatkit"
    values:
      title: "RDATKit"
      description: "<u>R</u>NA <u>Dat</u>aset Tool<u>Kit</u>"
      repo: "hitrace/RDATKit"
      root: "/RDATKit/"


# Build settings
markdown: kramdown
permalink: pretty


# Markdown Processors
kramdown:
  input: GFM

  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
